language: node_js
node_js:
  - '0.12'
  - '0.11'
  - '0.10'
  - 'iojs'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-distributions-io' ]; then cd .. && eval "mv $currentfolder generator-distributions-io" && cd generator-distributions-io; fi
after_script:
  - npm run coveralls
